import mongoose, { Schema, Document } from "mongoose";

/** Single entry in a resume's edit timeline. Appended whenever a material
 *  field (name / targetRole / file / tags) changes. v1: just a short
 *  human-readable summary string — a real per-field diff is a later pass. */
export interface IResumeVersion {
  timestamp: Date;
  summary: string;
}

export interface IResume extends Document {
  userId: mongoose.Types.ObjectId;
  name: string;
  targetRole: string;
  isProtected: boolean;
  tags: string[];
  fileName: string;
  fileUrl: string;
  filePublicId: string;
  uploadDate: Date;
  /** When this resume was generated by the AI Tailor, points at the user's
   *  primary resume AT THE TIME of tailoring. Lets the Resumes page render
   *  tailored variants nested under their base. Null for hand-uploaded
   *  resumes and legacy tailored resumes created before this field existed. */
  baseResumeId: mongoose.Types.ObjectId | null;
  /** TailorSession that produced this resume, when applicable. */
  tailorSessionId: mongoose.Types.ObjectId | null;
  /** Edit history — newest entries appended at the end. */
  versions: IResumeVersion[];
  createdAt: Date;
  updatedAt: Date;
}

const resumeVersionSchema = new Schema<IResumeVersion>(
  {
    timestamp: { type: Date, default: Date.now },
    summary: { type: String, default: "", trim: true },
  },
  { _id: false }
);

const resumeSchema = new Schema<IResume>(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
    name: { type: String, required: true, trim: true },
    targetRole: { type: String, default: "", trim: true },
    isProtected: { type: Boolean, default: false },
    tags: { type: [String], default: [] },
    fileName: { type: String, default: "", trim: true },
    fileUrl: { type: String, default: "" },
    filePublicId: { type: String, default: "" },
    uploadDate: { type: Date, default: Date.now },
    baseResumeId: { type: Schema.Types.ObjectId, ref: "Resume", default: null, index: true },
    tailorSessionId: { type: Schema.Types.ObjectId, ref: "TailorSession", default: null, index: true },
    versions: { type: [resumeVersionSchema], default: [] },
  },
  { timestamps: true }
);

export const Resume = mongoose.model<IResume>("Resume", resumeSchema);
